In [17]:
import numpy as np
from sklearn import preprocessing

sample_data= np.array([[ 0.12, 13.2, 14.3],
                      [-20, 21.4, -22],
                      [-31, 32.2, -0.33],
                      [41.0, 42.0, 43.0]])
sample_data

array([[  0.12,  13.2 ,  14.3 ],
       [-20.  ,  21.4 , -22.  ],
       [-31.  ,  32.2 ,  -0.33],
       [ 41.  ,  42.  ,  43.  ]])

In [4]:
sample_data.shape

(4, 3)

In [18]:
# Teknik Binarisasition

processor = preprocessing.Binarizer(threshold=0.33)# threshold untuk mengatur batas
binarised_data= preprocessing.binarize(sample_data)

binarised_data



array([[1., 1., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 1., 1.]])

In [19]:
#Teknik Scalling
# mereprsentasikan data asli dengan skala tertentu

preprocessor = preprocessing.MinMaxScaler(feature_range=(0 , 1)) #feature ramge berfungsi sebagai pengatur skala data
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)

scaled_data

array([[0.43222222, 0.        , 0.55846154],
       [0.15277778, 0.28472222, 0.        ],
       [0.        , 0.65972222, 0.33338462],
       [1.        , 1.        , 1.        ]])

In [20]:
#melakukan langsung fit dan transform

cara_lain = preprocessor.fit_transform(sample_data)
cara_lain

array([[0.43222222, 0.        , 0.55846154],
       [0.15277778, 0.28472222, 0.        ],
       [0.        , 0.65972222, 0.33338462],
       [1.        , 1.        , 1.        ]])

In [22]:
#Teknik Normalisation

L1_normalised = preprocessing.normalize(sample_data, norm = 'l1') #norm l1 akan berasosiasi dengan teknik Least absolute deviation
L1_normalised

array([[ 0.00434468,  0.47791455,  0.51774077],
       [-0.31545741,  0.33753943, -0.34700315],
       [-0.48795844,  0.50684716, -0.0051944 ],
       [ 0.32539683,  0.33333333,  0.34126984]])

In [23]:
L2_normalised = preprocessing.normalize(sample_data, norm = 'l2') #norm l2 akan berasosiasi dengan teknik Least squre
L2_normalised

array([[ 0.00616607,  0.67826721,  0.73478948],
       [-0.54595923,  0.58417637, -0.60055515],
       [-0.69353679,  0.72038338, -0.00738281],
       [ 0.56349736,  0.5772412 ,  0.59098504]])