In [28]:
import pandas as pd

sensus = {'tinggi' : [160 , 155, 170, 172, 165, 140, 159, 150, 160, 165],
          'berat' : [60, 55, 70, 65, 60, 40, 55, 60, 55, 60],
          'JK' : ['PRIA', 'PRIA', 'PRIA', 'PRIA', 'PRIA','WANITA','WANITA','WANITA','WANITA','WANITA']}

sensus_df = pd.DataFrame(sensus)
sensus_df


tinggi  berat      JK
0     160     60    PRIA
1     155     55    PRIA
2     170     70    PRIA
3     172     65    PRIA
4     165     60    PRIA
5     140     40  WANITA
6     159     55  WANITA
7     150     60  WANITA
8     160     55  WANITA
9     165     60  WANITA

In [29]:
# PENGELOMPOKKAN DATA FEATURES DAN TARGET
import numpy as np

x_train = np.array(sensus_df[['tinggi', 'JK']])
y_train = np.array(sensus_df['berat'])

print(f'x_train:\n{x_train}\n')
print(f'y_train: {y_train}')

x_train:
[[160 'PRIA']
 [155 'PRIA']
 [170 'PRIA']
 [172 'PRIA']
 [165 'PRIA']
 [140 'WANITA']
 [159 'WANITA']
 [150 'WANITA']
 [160 'WANITA']
 [165 'WANITA']]

y_train: [60 55 70 65 60 40 55 60 55 60]


In [30]:
#preprocess Dataset
#Konversi label menjadi numerik biner

x_train_transposed = np.transpose(x_train) #pengubahan baris menjadi kolom dan kolom menjadi baris

print(f'x_train:\n{x_train}\n')
print(f'x_train_transposed:\n{x_train_transposed}')

x_train:
[[160 'PRIA']
 [155 'PRIA']
 [170 'PRIA']
 [172 'PRIA']
 [165 'PRIA']
 [140 'WANITA']
 [159 'WANITA']
 [150 'WANITA']
 [160 'WANITA']
 [165 'WANITA']]

x_train_transposed:
[[160 155 170 172 165 140 159 150 160 165]
 ['PRIA' 'PRIA' 'PRIA' 'PRIA' 'PRIA' 'WANITA' 'WANITA' 'WANITA' 'WANITA'
  'WANITA']]


In [31]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(x_train_transposed[1]) #index ke 1 satu karena posisi nama jk

print(f'jk: {x_train_transposed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')


jk: ['PRIA' 'PRIA' 'PRIA' 'PRIA' 'PRIA' 'WANITA' 'WANITA' 'WANITA' 'WANITA'
 'WANITA']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [32]:
#mengubah bentuk array multi dimensi menjadi single
jk_binarised = jk_binarised.flatten()
jk_binarised


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [33]:
#mentranpose kembali agar menjadi bentuk data semula
x_train_transposed[1] = jk_binarised
x_train = x_train_transposed.transpose()

print(f'x_train_transposed:\n{x_train_transposed}\n')
print(f'x_train:\n{x_train}')
#

x_train_transposed:
[[160 155 170 172 165 140 159 150 160 165]
 [0 0 0 0 0 1 1 1 1 1]]

x_train:
[[160 0]
 [155 0]
 [170 0]
 [172 0]
 [165 0]
 [140 1]
 [159 1]
 [150 1]
 [160 1]
 [165 1]]


In [34]:
#TRAINING KNN REGRESSION MODEL

from sklearn.neighbors import KNeighborsRegressor

k= 5
model= KNeighborsRegressor(n_neighbors = k)
model.fit(x_train, y_train)

KNeighborsRegressor()

In [35]:
#Prediksi Berat Badan

x_new = np.array([[155, 1]])
x_new

array([[155,   1]])

In [36]:
y_pred = model.predict(x_new)
y_pred

array([57.])

In [37]:
#Evaluasi KNN Regression Model

x_test = np.array([[168, 0], [190, 0], [150, 1], [160, 1]])
y_test = np.array([65, 96, 52, 67])

print(f'x_test:\n{x_test}\n')
print(f'y_test: {y_test}')

x_test:
[[168   0]
 [190   0]
 [150   1]
 [160   1]]

y_test: [65 96 52 67]


In [38]:
y_pred = model.predict(x_test)
y_pred

array([63., 63., 53., 58.])

In [39]:
#Metric Evaluasi Coefficient of determination atau R2

from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print(f'R-squared: {r_squared}') #SEMAKIN MENYEBAR SEMAKIN BAGUS


R-squared: -0.13636363636363646


In [40]:
#Mean Absolute Error (MAE)

from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

print(f'MAE: {MAE}') #SEMAKIN KECIL SEMAKIN BAGUS

MAE: 11.25


In [41]:
#MEAN SQUARE ERROR (MSE)

from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)

print(f'MSE: {MSE}') #SEMAKIN KECIL SEMAKIN BAGUS


MSE: 293.75


In [42]:
#Permasalahan Scalling pada features, serta pemecahan masalahnya


#terdapat pada cahannel indonesia belajar chapter 7


In [43]:
#MENERAPKAN FEATURE SCALLING PADA KNN yang akan membuat performa model menjadi lebih baik

#DATASET
#TRAINING SET
x_train = np.array([[160, 0],[155, 0],[170, 0],[172, 0],[165, 0],[140, 1],[159, 1],[150, 1],[160, 1],[165, 1]])

y_train = np.array([60,55,70,65,60,40,55,60,55,60])

#TEST SET
x_test = np.array([[168, 0], [190, 0], [150, 1], [160, 1]])
y_test = np.array([65, 96, 52, 67])




In [44]:
#Features Scalling
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

x_train_scalled = ss.fit_transform(x_train)
x_test_scalled = ss.transform(x_test)

print(f'x_train_scalled:\n{x_train_scalled}\n')
print(f'x_test_scalled:\n{x_test_scalled}\n')



x_train_scalled:
[[ 0.04421577 -1.        ]
 [-0.50848134 -1.        ]
 [ 1.14960999 -1.        ]
 [ 1.37068883 -1.        ]
 [ 0.59691288 -1.        ]
 [-2.16657267  1.        ]
 [-0.06632365  1.        ]
 [-1.06117845  1.        ]
 [ 0.04421577  1.        ]
 [ 0.59691288  1.        ]]

x_test_scalled:
[[ 0.92853115 -1.        ]
 [ 3.36039843 -1.        ]
 [-1.06117845  1.        ]
 [ 0.04421577  1.        ]]



In [45]:
#Training dan Evaluasi Model

model.fit(x_train_scalled, y_train)
y_pred = model.predict(x_test_scalled)

MAE = mean_absolute_error(y_test, y_pred)
print(f'MAE: {MAE}')

MSE = mean_squared_error(y_test, y_pred)
print(f'MSE: {MSE}')

MAE: 11.75
MSE: 295.75
