In [1]:
import pandas as pd

sensus = {'tinggi' : [160 , 155, 170, 172, 165, 140, 159, 150, 160, 165],
          'berat' : [60, 55, 70, 65, 60, 40, 55, 60, 55, 60],
          'JK' : ['PRIA', 'PRIA', 'PRIA', 'PRIA', 'PRIA','WANITA','WANITA','WANITA','WANITA','WANITA']}

sensus_df = pd.DataFrame(sensus)
sensus_df


tinggi  berat      JK
0     160     60    PRIA
1     155     55    PRIA
2     170     70    PRIA
3     172     65    PRIA
4     165     60    PRIA
5     140     40  WANITA
6     159     55  WANITA
7     150     60  WANITA
8     160     55  WANITA
9     165     60  WANITA

In [2]:
# PENGELOMPOKKAN DATA FEATURES DAN TARGET
import numpy as np

x_train = np.array(sensus_df[['tinggi', 'JK']])
y_train = np.array(sensus_df['berat'])

print(f'x_train:\n{x_train}\n')
print(f'y_train: {y_train}')

x_train:
[[160 'PRIA']
 [155 'PRIA']
 [170 'PRIA']
 [172 'PRIA']
 [165 'PRIA']
 [140 'WANITA']
 [159 'WANITA']
 [150 'WANITA']
 [160 'WANITA']
 [165 'WANITA']]

y_train: [60 55 70 65 60 40 55 60 55 60]


In [3]:
#preprocess Dataset
#Konversi label menjadi numerik biner

x_train_transposed = np.transpose(x_train) #pengubahan baris menjadi kolom dan kolom menjadi baris

print(f'x_train:\n{x_train}\n')
print(f'x_train_transposed:\n{x_train_transposed}')

x_train:
[[160 'PRIA']
 [155 'PRIA']
 [170 'PRIA']
 [172 'PRIA']
 [165 'PRIA']
 [140 'WANITA']
 [159 'WANITA']
 [150 'WANITA']
 [160 'WANITA']
 [165 'WANITA']]

x_train_transposed:
[[160 155 170 172 165 140 159 150 160 165]
 ['PRIA' 'PRIA' 'PRIA' 'PRIA' 'PRIA' 'WANITA' 'WANITA' 'WANITA' 'WANITA'
  'WANITA']]


In [11]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(x_train_transposed[1]) #index ke 1 satu karena posisi nama jk

print(f'jk: {x_train_transposed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')


jk: ['PRIA' 'PRIA' 'PRIA' 'PRIA' 'PRIA' 'WANITA' 'WANITA' 'WANITA' 'WANITA'
 'WANITA']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [12]:
#mengubah bentuk array multi dimensi menjadi single
jk_binarised = jk_binarised.flatten()
jk_binarised


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [15]:
#mentranpose kembali agar menjadi bentuk data semula
x_train_transposed[1] = jk_binarised
x_train = x_train_transposed.transpose()

print(f'x_train_transposed:\n{x_train_transposed}\n')
print(f'x_train:\n{x_train}')
#

x_train_transposed:
[[160 155 170 172 165 140 159 150 160 165]
 [0 0 0 0 0 1 1 1 1 1]]

x_train:
[[160 0]
 [155 0]
 [170 0]
 [172 0]
 [165 0]
 [140 1]
 [159 1]
 [150 1]
 [160 1]
 [165 1]]
